--Q1. What is the total revenue (Order_Value) generated by each City?
SELECT "City", 
       ROUND(SUM("Order_Value")::numeric,2) AS total_revenue
FROM customer
GROUP BY "City"
ORDER BY total_revenue DESC;

--Q2. Which orders had a discount applied but still had delivery time greater than average?
SELECT "Order_ID", "Delivery_Time_Min", "Order_Value"
FROM customer
WHERE "Discount_Applied" = 1 
  AND "Delivery_Time_Min" >= (SELECT AVG("Delivery_Time_Min") FROM customer);

--Q3. Top 5 product categories with highest average customer rating
SELECT "Product_Category", 
       ROUND(AVG("Customer_Rating")::numeric,2) AS avg_customer_rating
FROM customer
GROUP BY "Product_Category"
ORDER BY AVG("Customer_Rating") DESC
LIMIT 5;

--Q4. Average Delivery Time: discount vs no discount
SELECT "Discount_Applied", 
       ROUND(AVG("Delivery_Time_Min")::numeric,2) AS avg_delivery_time
FROM customer
GROUP BY "Discount_Applied";

--Q5. High vs Low rated delivery partners - SLA compliance
SELECT 
    CASE 
        WHEN "Delivery_Partner_Rating" >= 4 THEN 'High Rated (4+)'
        ELSE 'Low Rated (<4)'
    END AS partner_rating_group,
    COUNT("Order_ID") AS total_orders,
    ROUND(AVG("Delivery_Time_Min")::numeric,2) AS avg_delivery_time,
    ROUND(100.0 * SUM(CASE WHEN "Delivery_Time_Min" > 15 THEN 1 ELSE 0 END)/COUNT(*),2) AS sla_breach_pct
FROM customer
GROUP BY partner_rating_group
ORDER BY sla_breach_pct DESC;

--Q6. Top 5 categories with highest delayed order %
SELECT "Product_Category",
       ROUND(100.0 * SUM(CASE WHEN "Delivery_Time_Min" > 15 THEN 1 ELSE 0 END)/COUNT(*),2) AS delay_rate
FROM customer
GROUP BY "Product_Category"
ORDER BY delay_rate DESC
LIMIT 5;

--Q7. Distance segments with average delivery time
WITH distance_type AS (
SELECT "Order_ID", "Distance_Km", "Delivery_Time_Min",
CASE 
    WHEN "Distance_Km" <= 2 THEN 'Near'
    WHEN "Distance_Km" BETWEEN 2 AND 5 THEN 'Medium'
    ELSE 'Far'
    END AS distance_segment
FROM customer)
SELECT distance_segment, 
       COUNT(*) AS number_of_orders,
       ROUND(AVG("Delivery_Time_Min")::numeric,2) AS avg_delivery_time
FROM distance_type 
GROUP BY distance_segment;

--Q8. Top 3 categories per city
WITH category_counts AS (
    SELECT "City",
           "Product_Category",
           COUNT("Order_ID") AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY "City" ORDER BY COUNT("Order_ID") DESC) AS category_rank
    FROM customer
    GROUP BY "City", "Product_Category"
)
SELECT category_rank, "City", "Product_Category", total_orders
FROM category_counts
WHERE category_rank <= 3;

--Q9. Low customer rating vs delivery time/distance
SELECT 
    CASE 
        WHEN "Customer_Rating" < 3 THEN 'Low Rating (<3)'
        ELSE 'Good Rating (3+)'
    END AS rating_group,
    COUNT("Order_ID") AS total_orders,
    ROUND(AVG("Delivery_Time_Min")::numeric,2) AS avg_delivery_time,
    ROUND(AVG("Distance_Km")::numeric,2) AS avg_distance
FROM customer
GROUP BY rating_group;

--Q10. SLA breach % by City
SELECT 
    "City",
    COUNT("Order_ID") AS total_orders,
    SUM(CASE WHEN "Delivery_Time_Min" > 15 THEN 1 ELSE 0 END) AS delayed_orders,
    ROUND(100.0 * SUM(CASE WHEN "Delivery_Time_Min" > 15 THEN 1 ELSE 0 END)/COUNT(*),2) AS sla_breach_pct
FROM customer
GROUP BY "City"
ORDER BY sla_breach_pct DESC;

--Q11. Company-wise SLA breach comparison
SELECT "Company",
       COUNT("Order_ID") AS total_orders,
       ROUND(AVG("Delivery_Time_Min")::numeric,2) AS avg_delivery_time,
       ROUND(100.0 * SUM(CASE WHEN "Delivery_Time_Min" > 15 THEN 1 ELSE 0 END)/COUNT(*),2) AS sla_breach_pct
FROM customer
GROUP BY "Company"
ORDER BY sla_breach_pct DESC;

--Q12. Which Payment Method has the highest average order value?
SELECT "Payment_Method",
       ROUND(AVG("Order_Value")::numeric,2) AS avg_order_value,
       COUNT("Order_ID") AS total_orders
FROM customer
GROUP BY "Payment_Method"
ORDER BY avg_order_value DESC;

--Q13. Does customer age group affect delivery delays?
SELECT 
    CASE 
        WHEN "Customer_Age" < 25 THEN '18-24'
        WHEN "Customer_Age" BETWEEN 25 AND 40 THEN '25-40'
        WHEN "Customer_Age" BETWEEN 41 AND 60 THEN '41-60'
        ELSE '60+'
    END AS age_group,
    COUNT("Order_ID") AS total_orders,
    ROUND(AVG("Delivery_Time_Min")::numeric,2) AS avg_delivery_time,
    ROUND(100.0 * SUM(CASE WHEN "Delivery_Time_Min" > 15 THEN 1 ELSE 0 END)/COUNT(*),2) AS sla_breach_pct
FROM customer
GROUP BY age_group
ORDER BY age_group;

--Q14. Does items_count in an order affect delivery time?
SELECT 
    CASE 
        WHEN "Items_Count" <= 3 THEN 'Low (1-3 items)'
        WHEN "Items_Count" BETWEEN 4 AND 7 THEN 'Medium (4-7 items)'
        ELSE 'High (8+ items)'
    END AS item_count_group,
    ROUND(AVG("Delivery_Time_Min")::numeric,2) AS avg_delivery_time,
    COUNT("Order_ID") AS total_orders
FROM customer
GROUP BY item_count_group
ORDER BY avg_delivery_time DESC;